name: tdlib-build


  
        
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Manual Run'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
  push:
    paths:
      - '.github/workflows/td-version.json'
      - '.github/workflows/build-tdlib.yml'
      - 'https://github.com/tdlib/td'

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/td-version.json'
          prefix: td
      - name: updata
        run: |
           sudo apt-get install openjdk-17-jdk
      - name: setup
        run: |
          sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev ninja-build 
         

      - name: clone
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git checkout ${{ env.td_commit_hash }}
          git show --summary

      - name: setup td
        run: |
          cd td/example/android
          ./check-environment.sh
          ./fetch-sdk.sh
          ./build-openssl.sh
          ./build-tdlib.sh '' '' '' '' 'JSON'
      

