name: tdlib-build

on:
  push:
    paths:
      - '.github/workflows/td-version.json'
      - '.github/workflows/build-tdlib.yml'

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/td-version.json'
          prefix: td

      - name: setup
        run: |
          sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev ninja-build

      
      
      - name: clone
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git checkout ${{ env.td_commit_hash }}
          git show --summary
      - name: check-environment
        run: |
          cd td/example/android
          ./check-environment.sh
      - name: java update
        run: |
          sudo apt install openjdk-17-jre
          sudo apt install openjdk-17-jdk
          export JAVA_HOME="/usr/lib/jvm/openjdk-17
          export PATH="$PATH:$JAVA_HOME/bin

      - name: sdk
        run: |
          java --version
          cd td/example/android
          ./fetch-sdk.sh
      - name: openssl
        run: |
          cd td/example/android
          ./build-openssl.sh  
      - name: tdlib build
        run: |
          cd td/example/android
          ./build-tdlib.sh '' '' '' '' 'JSON'
